### ISSUE TITLE
Re-enabling ImJoy/ImageJ in current Matchboxscope

### ISSUE THREAD

**Issue by beniroquai** [Matchboxscope/matchboxscope-simplecamera#1]
@oeway, we have rewritten the firmware for the ESP32-CAM to become a mini microscope. I have added imjoy/imagej.js support in the current version. However, the image does not open in a new frame. I think for you it would be a 10 seconds task. Would you mind to have a look why the image opens in the same frame? The file to observe is this here: https://github.com/Matchboxscope/matchboxscope-simplecamera/blob/matchboxscope/main/index.html In order to debug it, you can create a file named 

`status` with the content:

```json
{"lamp":100,"autolamp":1,"min_frame_time":0,"framesize":8,"quality":12,"xclk":8,"brightness":-1,"contrast":0,"saturation":0,"sharpness":0,"special_effect":0,"wb_mode":0,"awb":0,"awb_gain":1,"aec":0,"aec2":1,"ae_level":-1,"aec_value":797,"agc":0,"agc_gain":5,"gainceiling":2,"bpc":0,"wpc":1,"raw_gma":1,"lenc":0,"vflip":0,"hmirror":0,"dcw":1,"colorbar":0,"cam_name":"Matchboxscope","code_ver":"Apr 17 2023 @ 09:18:49","rotate":"0","stream_url":"http://192.168.137.69:81/","anglerfishSlider":"1"}
```

Currently it looks like this: 
![image](https://user-images.githubusercontent.com/4345528/232536192-e14f08e0-e16e-44d1-a4f8-1ced38223aba.png)

Also, I managed to upload frames directly to  Github (from c-code). Perhaps we could also keep up the thread on interacting with hypha again ;-)

**Comment by oeway** [comment]
Hi, it might because that you set the image name in https://github.com/Matchboxscope/matchboxscope-simplecamera/blob/matchboxscope/main/index.html#L589 Try to use a randomized name?

**Comment by beniroquai** [comment]
Thanks! Seems to be working now. Maybe a browser cache thing! Thanks a lot @oeway ! :)
